// io_uring constants from linux/io_uring.h (kernel 6.0+).

package ublk

const (
	IORING_OP_READ_FIXED  = 4
	IORING_OP_WRITE_FIXED = 5
	IORING_OP_URING_CMD   = 46

	IORING_SETUP_IOPOLL        = 1 << 0
	IORING_SETUP_SQPOLL        = 1 << 1
	IORING_SETUP_SQ_AFF        = 1 << 2
	IORING_SETUP_COOP_TASKRUN  = 1 << 8
	IORING_SETUP_SQE128        = 1 << 10
	IORING_SETUP_SINGLE_ISSUER = 1 << 12
	IORING_SETUP_DEFER_TASKRUN = 1 << 13

	IORING_ENTER_GETEVENTS = 1 << 0

	IOSQE_FIXED_FILE = 1 << 0

	IORING_OFF_SQ_RING = 0x00000000
	IORING_OFF_CQ_RING = 0x08000000
	IORING_OFF_SQES    = 0x10000000
)
