// Code generated by go generate; DO NOT EDIT.
// Generated on 2026-01-31T06:08:01Z for linux/amd64.
//
// Source: linux/io_uring.h (kernel headers)
//
// To regenerate (requires liburing-dev):
//   make generate

//go:build linux

package ublk

// io_uring operation codes from linux/io_uring.h.
const (
	IORING_OP_READ_FIXED  = 4
	IORING_OP_WRITE_FIXED = 5
	IORING_OP_URING_CMD   = 46
)

// io_uring setup flags from linux/io_uring.h.
const (
	IORING_SETUP_IOPOLL        = 1
	IORING_SETUP_SQPOLL        = 2
	IORING_SETUP_SQ_AFF        = 4
	IORING_SETUP_COOP_TASKRUN  = 256
	IORING_SETUP_SQE128        = 1024
	IORING_SETUP_SINGLE_ISSUER = 4096
	IORING_SETUP_DEFER_TASKRUN = 8192
)

// io_uring enter flags from linux/io_uring.h.
const (
	IORING_ENTER_GETEVENTS = 1
)

// SQE flags from linux/io_uring.h.
const (
	IOSQE_FIXED_FILE = 1
)

// Mmap offsets from linux/io_uring.h.
const (
	IORING_OFF_SQ_RING = 0x0
	IORING_OFF_CQ_RING = 0x8000000
	IORING_OFF_SQES    = 0x10000000
)
