//go:build cgo
// +build cgo

package ublk

/*
#cgo pkg-config: liburing

#include <liburing.h>
*/
import "C"

// Constants from liburing/kernel headers
const (
	IORING_OP_URING_CMD = C.IORING_OP_URING_CMD
)

// IORING_SETUP flags
const (
	IORING_SETUP_IOPOLL     = C.IORING_SETUP_IOPOLL
	IORING_SETUP_SQPOLL     = C.IORING_SETUP_SQPOLL
	IORING_SETUP_SQ_AFF     = C.IORING_SETUP_SQ_AFF
	IORING_SETUP_CQSIZE     = C.IORING_SETUP_CQSIZE
	IORING_SETUP_CLAMP      = C.IORING_SETUP_CLAMP
	IORING_SETUP_ATTACH_WQ  = C.IORING_SETUP_ATTACH_WQ
	IORING_SETUP_R_DISABLED = C.IORING_SETUP_R_DISABLED
)

// IORING_ENTER flags
const (
	IORING_ENTER_GETEVENTS = C.IORING_ENTER_GETEVENTS
	IORING_ENTER_SQ_WAKEUP = C.IORING_ENTER_SQ_WAKEUP
	IORING_ENTER_SQ_WAIT   = C.IORING_ENTER_SQ_WAIT
)

// SQE flags
const (
	IOSQE_FIXED_FILE    = C.IOSQE_FIXED_FILE
	IOSQE_IO_DRAIN      = C.IOSQE_IO_DRAIN
	IOSQE_IO_LINK       = C.IOSQE_IO_LINK
	IOSQE_IO_HARDLINK   = C.IOSQE_IO_HARDLINK
	IOSQE_ASYNC         = C.IOSQE_ASYNC
	IOSQE_BUFFER_SELECT = C.IOSQE_BUFFER_SELECT
)

// CQE flags
const (
	IORING_CQE_F_BUFFER        = C.IORING_CQE_F_BUFFER
	IORING_CQE_F_MORE          = C.IORING_CQE_F_MORE
	IORING_CQE_F_SOCK_NONEMPTY = C.IORING_CQE_F_SOCK_NONEMPTY
)

// IORING_OFF constants for mmap offsets
const (
	IORING_OFF_SQ_RING = 0
	IORING_OFF_CQ_RING = 0x8000000
	IORING_OFF_SQES    = 0x10000000
)
