version: "2"

formatters:
  enable:
    - gofumpt

linters:
  default: none
  enable:
    - errcheck
    - gocritic
    - govet
    - ineffassign
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused

  exclusions:
    rules:
      - path: "_test\\.go$"
        linters: [errcheck]
      - path: "example/"
        linters: [errcheck]

run:
  go: "1.25"
